url: https://jessica-joly.github.io
baseurl:

# Site settings
title: Hello!
email: jessicajoly88@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFA07A
  secondary: FFE4C4
  secondary-dark: 333


# Team names, titles and social links
people:
- name: Jessica Joly
  pic: 1
  position: Software Developer
  social:
    - title: linkedin
      url: https://ca.linkedin.com/in/jessicajoly
    - title: github
      url: https://github.com/jessica-joly


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://ca.linkedin.com/in/jessicajoly
  - title: github
    url: https://github.com/jessica-joly


# Build settings
markdown: kramdown
permalink: pretty
