url: https://jessica-joly.github.io
baseurl:

# Site settings
title: Hello!
email: jessicajoly88@gmail.com
description: Jessica Joly's portfolio site. 
color:
  primary: ffa07a
  secondary: FFE4C4
  secondary-dark: 333


# Team names, titles and social links
people:
- name: Jessica Joly
  pic: 1
  position: Software Developer
  social:
    - title: linkedin
      url: https://ca.linkedin.com/in/jessicajoly
    - title: github
      url: https://github.com/jessica-joly


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://ca.linkedin.com/in/jessicajoly
  - title: github
    url: https://github.com/jessica-joly


# Build settings
markdown: kramdown
permalink: pretty
